version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./wordpress:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - "80:80"
    tty:  true
    restart: unless-stopped
    container_name: wordpress_nginx
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    tty:  true
    user: 1000:1000
    restart: unless-stopped
    volumes:
      - ./wordpress:/var/www
    container_name: app

