version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - "80:80"
    tty:  true
    restart: unless-stopped
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - app-network

  wordpress:
    image: wordpress:beta-php8.1-fpm-alpine
    tty:  true
    restart: unless-stopped
    volumes:
      - ./wordpress:/var/www/html
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - app-network

  mariadb:
    image: yobasystems/alpine-mariadb:latest
    tty:  true
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/lib/mysql/mysql-bin
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: mariadb
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
